spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.ytpuptgfhkizbiotiako
spring.datasource.password=YdRsk3sH5h1wk2ne
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false